pipeline {
    agent { label 'jenkins-agent' }

    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    environment {
        APP_NAME = "java-app"
        RELEASE = "1.0.0"
        DOCKER_USER = "prasannakumaryendluri45"
        DOCKER_CREDENTIALS = "dockerhub"

        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
    }

    stages {

        stage('Cleanup Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'github',
                url: 'https://github.com/prasannakumaryendluri-45/ci-cd-git-hub-maven-jenkins-sonarQube-argocd-K8s.git'
            }
        }

        stage('Build') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
                  steps {
                     script {
                        withSonarQubeEnv(credentialsId: 'jenkins-sonarqube_token') {
                           sh 'mvn sonar:sonar'
            }
        }
    }
}

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('my-java-cicd-project/java-app') {

                        docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS}") {

                            def image = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")

                            image.push()
                            image.push('latest')
                        }
                    }
                }
            }
        }
        stage("Trivy Scan") {
           steps {
               script {
	            sh ('docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image prasannakumaryendluri45/java-app:latest --no-progress --scanners vuln  --exit-code 0 --severity HIGH,CRITICAL --format table')
               }
           }
       }
        stage ('Cleanup Artifacts') {
           steps {
               script {
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker rmi ${IMAGE_NAME}:latest"
               }
          }
       }
    }
}
