pipeline {
    agent { label 'jenkins-agent' }

    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    stages {

        stage('Cleanup Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from SCM') {
            steps {
                git branch: 'main',
                credentialsId: 'github',
                url: 'https://github.com/prasannakumaryendluri-45/ci-cd-git-hub-maven-jenkins-sonarQube-argocd-K8s.git'
            }
        }

        stage('Build Application') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test Application') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('my-java-cicd-project/java-app') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
    }
}
