pipeline {
    agent { label 'jenkins-agent' }

    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    environment {
        APP_NAME = "java-app"
        RELEASE = "1.0.0"
        DOCKER_USER = "prasannakumaryendluri45"
        DOCKER_CREDENTIALS = "dockerhub"

        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
    }

    stages {

        stage('Cleanup Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main',
                credentialsId: 'github',
                url: 'https://github.com/prasannakumaryendluri-45/ci-cd-git-hub-maven-jenkins-sonarQube-argocd-K8s.git'
            }
        }

        stage('Build') {
    steps {
        dir('my-java-cicd-project/java-app') {
            sh 'mvn clean package -DskipTests'
        }
    }
}

        stage('Test') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('my-java-cicd-project/java-app') {
                    withSonarQubeEnv('sonarqube-server') {
                        sh 'mvn clean verify sonar:sonar'
                    }
                }
            }
        }

          stage('Quality Gate') {
    steps {
        timeout(time: 1, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: false
        }
    }
}
       
               stage('Build & Push Docker Image') {
      steps {
          script {
            dir('my-java-cicd-project/java-app') {

                docker.withRegistry('', 'dockerhub') {

                    sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest

                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }
}

        stage("Trivy Scan") {
            steps {
                script {
                    sh """
                    docker run -v /var/run/docker.sock:/var/run/docker.sock \
                    aquasec/trivy image ${IMAGE_NAME}:latest \
                    --no-progress \
                    --scanners vuln \
                    --exit-code 0 \
                    --severity HIGH,CRITICAL \
                    --format table
                    """
                }
            }
        }

        stage('Cleanup Artifacts') {
            steps {
                script {
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
                    sh "docker rmi ${IMAGE_NAME}:latest || true"
                }
            }
        }
    }
}
